---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:Maximuss88/kibana-role.git
    scm: git
    name: kibana-role
  - src: git@github.com:Maximuss88/filebeat-role.git
    scm: git
    name: filebeat-role
