---
  el:
    hosts:
      centos7_1:
        ansible_connection: docker
  deb:
    hosts:
      ubuntu_1:
        ansible_connection: docker
        
  local:
    hosts:
      localhost:
        ansible_connection: local

  fed:
    hosts:
      fedora_1:
        ansible_connection: docker

