---
all:
  hosts:
    el-instance:
      ansible_host: 51.250.23.168
      ansible_connection: ssh
      ansible_user: max
      
    k-instance:
      ansible_host: 51.250.30.167
      ansible_connection: ssh
      ansible_user: max
      
    f-instance:
      ansible_host: 51.250.30.217
      ansible_connection: ssh
      ansible_user: max
